In [1]:
import pandas as pd
import numpy as np
import sys
import optuna
# !{sys.executable} -m pip install category_encoders
from category_encoders.woe import WOEEncoder

C:\Users\khadk\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dict1={
    'feature':['A','B','C','C','B','B','A','C'],
    'target':[1,0,0,0,1,1,0,1]
}

In [3]:
df=pd.DataFrame(dict1)
df

  feature  target
0       A       1
1       B       0
2       C       0
3       C       0
4       B       1
5       B       1
6       A       0
7       C       1

In [4]:
X=df['feature']
Y=df['target']

In [5]:
woe=WOEEncoder()

In [6]:
res=woe.fit_transform(X,Y)
res

    feature
0  0.000000
1  0.405465
2 -0.405465
3 -0.405465
4  0.405465
5  0.405465
6  0.000000
7 -0.405465

In [7]:
df['Encoded']=res

In [8]:
df

  feature  target   Encoded
0       A       1  0.000000
1       B       0  0.405465
2       C       0 -0.405465
3       C       0 -0.405465
4       B       1  0.405465
5       B       1  0.405465
6       A       0  0.000000
7       C       1 -0.405465